CREATE TABLE IF NOT EXISTS "Device" (
	"id" INTEGER NOT NULL UNIQUE,
	"serial" VARCHAR NOT NULL UNIQUE,
	"name" VARCHAR,
	"userId" INTEGER DEFAULT NULL,
	"lastUpdate" TIMESTAMP DEFAULT NOW(),
	PRIMARY KEY("id"),
	FOREIGN KEY ("userId") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "User" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"email" VARCHAR NOT NULL UNIQUE,
	"password" VARCHAR NOT NULL,
	"lastLogin" DATETIME,
	"roleId" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("roleId") REFERENCES "Role"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

/* Die einzelnen SensorTypen */
CREATE TABLE IF NOT EXISTS "SensorType" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL UNIQUE,
	"model" VARCHAR,
	"type" VARCHAR NOT NULL,
	"values" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Role" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"code" VARCHAR NOT NULL,
	"description" VARCHAR,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Paket" (
	"id" INTEGER NOT NULL UNIQUE,
	"created" TIMESTAMP NOT NULL DEFAULT NOW(),
	"serial" VARCHAR NOT NULL,
	"deviceId" INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY ("deviceId") REFERENCES "Device"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "PaketEntry" (
	"id" INTEGER NOT NULL UNIQUE,
	"created" TIMESTAMP NOT NULL,
	"paketId" INTEGER NOT NULL,
	"sensorTypeId" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("sensorTypeId") REFERENCES "SensorType"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("paketId") REFERENCES "Paket"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Job" (
	"id" INTEGER NOT NULL UNIQUE,
	"created" TIMESTAMP NOT NULL,
	"jobTypeId" INTEGER NOT NULL,
	"success" BOOLEAN NOT NULL DEFAULT 0,
	"startTime" TIMESTAMP,
	"endTime" TIMESTAMP,
	"finished" BOOLEAN,
	"userId" INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "JobType" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"description" VARCHAR NOT NULL,
	"active" BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id") REFERENCES "Job"("jobTypeId")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DeviceKey" (
	"id" INTEGER NOT NULL UNIQUE,
	"type" VARCHAR NOT NULL,
	"key" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);
